name: CI

on:
  push:
    branches: [ main, feature-ui-layout ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint (if configured)
        run: |
          if [ -f package.json ] && npm run | grep -q "lint"; then
            npm run lint --if-present || true
          else
            echo "No lint script detected, skipping"
          fi

      - name: Run tests (if present)
        run: |
          if npm run | grep -q "test"; then
            npm test --if-present || true
          else
            echo "No tests detected, skipping"
          fi

      - name: Build
        run: npm run build --if-present
